#!/bin/bash
set -e

echo "=========================================="
echo "Canvas LMS Builder Script"
echo "=========================================="
echo ""

CANVAS_SRC_HOST="/opt/canvas-src"
CANVAS_SRC_VOLUME="/var/canvas"
CONFIG_HOST="/opt/config"
CONFIG_VOLUME="/var/canvas/config"

# ===========================================
# Step 1: Sync Canvas Source Code
# ===========================================
echo "[1/7] Syncing Canvas source code..."

if [ -d "$CANVAS_SRC_HOST" ] && [ "$(ls -A $CANVAS_SRC_HOST 2>/dev/null)" ]; then
    echo "  → Found source on host, copying to volume..."
    rsync -av --delete --exclude='.git' --exclude='node_modules' --exclude='vendor' \
        "$CANVAS_SRC_HOST/" "$CANVAS_SRC_VOLUME/"
    echo "  ✓ Source copied: host → volume"
elif [ -d "$CANVAS_SRC_VOLUME" ] && [ -f "$CANVAS_SRC_VOLUME/Gemfile" ]; then
    echo "  → Found source in volume, copying to host..."
    mkdir -p "$CANVAS_SRC_HOST"
    rsync -av "$CANVAS_SRC_VOLUME/" "$CANVAS_SRC_HOST/"
    echo "  ✓ Source copied: volume → host"
else
    echo "  ✗ ERROR: No Canvas source found!"
    echo "    Please place Canvas source in ./canvas-src/ on host"
    exit 1
fi

cd "$CANVAS_SRC_VOLUME"

# ===========================================
# Step 2: Sync Config Directory
# ===========================================
echo ""
echo "[2/7] Syncing config directory..."

if [ -d "$CONFIG_HOST" ] && [ "$(ls -A $CONFIG_HOST 2>/dev/null)" ]; then
    echo "  → Found configs on host, copying to volume..."
    mkdir -p "$CONFIG_VOLUME"
    rsync -av "$CONFIG_HOST/" "$CONFIG_VOLUME/"
    echo "  ✓ Configs copied: host → volume"
elif [ -d "$CONFIG_VOLUME" ] && [ "$(ls -A $CONFIG_VOLUME/*.yml 2>/dev/null)" ]; then
    echo "  → Found configs in volume, copying to host..."
    mkdir -p "$CONFIG_HOST"
    rsync -av "$CONFIG_VOLUME/" "$CONFIG_HOST/"
    echo "  ✓ Configs copied: volume → host"
else
    echo "  ⚠ No configs found, will use Canvas examples"
    echo "  → Copying .example files to host..."
    mkdir -p "$CONFIG_HOST"
    for example in "$CONFIG_VOLUME"/*.example; do
        if [ -f "$example" ]; then
            basename=$(basename "$example" .example)
            cp "$example" "$CONFIG_HOST/${basename}.example"
        fi
    done
    echo "  ✓ Config examples copied to host"
    echo "  ⚠ Please edit files in ./config/ before running runtime"
fi

# ===========================================
# Step 3: Ensure canvasuser exists
# ===========================================
echo ""
echo "[3/7] Ensuring canvasuser exists..."

if ! id -u canvasuser > /dev/null 2>&1; then
    useradd --create-home --shell /bin/bash --comment "Canvas LMS User" canvasuser
    echo "  ✓ canvasuser created"
else
    echo "  ✓ canvasuser already exists"
fi

# ===========================================
# Step 4: Create Directory Structure
# ===========================================
echo ""
echo "[4/7] Creating directory structure..."

mkdir -p \
    log \
    tmp/pids \
    public/assets \
    public/dist/brandable_css \
    app/stylesheets/brandable_css_brands

touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss
touch Gemfile.lock
touch log/production.log

# Set ownership to canvasuser early
chown -R canvasuser:canvasuser "$CANVAS_SRC_VOLUME"

echo "  ✓ Directories created and owned by canvasuser"

# ===========================================
# Step 5: Bundle Install (as canvasuser)
# ===========================================
echo ""
echo "[5/7] Installing Ruby dependencies..."

if [ -f "Gemfile" ]; then
    echo "  → Running bundle install as canvasuser..."
    su - canvasuser -c "cd $CANVAS_SRC_VOLUME && \
        bundle config set --local path 'vendor/bundle' && \
        bundle config set --local without 'development test' && \
        bundle install --jobs 4 --retry 3"
    echo "  ✓ Bundle install completed"
else
    echo "  ✗ ERROR: Gemfile not found"
    exit 1
fi

# ===========================================
# Step 6: Yarn Install (as canvasuser)
# ===========================================
echo ""
echo "[6/7] Installing Node dependencies..."

if [ -f "package.json" ]; then
    echo "  → Running yarn install as canvasuser..."
    su - canvasuser -c "cd $CANVAS_SRC_VOLUME && \
        yarn install --pure-lockfile 2>/dev/null || yarn install"
    echo "  ✓ Yarn install completed"
else
    echo "  ✗ ERROR: package.json not found"
    exit 1
fi

# ===========================================
# Step 7: Verify Permissions
# ===========================================
echo ""
echo "[7/7] Verifying file permissions..."

# Double-check critical directories are owned by canvasuser
chown -R canvasuser:canvasuser \
    "$CANVAS_SRC_VOLUME/log" \
    "$CANVAS_SRC_VOLUME/tmp" \
    "$CANVAS_SRC_VOLUME/public" \
    2>/dev/null || true

echo "  ✓ Permissions verified"

# ===========================================
# Summary
# ===========================================
echo ""
echo "=========================================="
echo "✓ Build completed successfully!"
echo "=========================================="
echo ""
echo "Volume prepared at: $CANVAS_SRC_VOLUME"
echo "All installations run as: canvasuser"
echo ""
echo "Next steps:"
echo "  1. Review/edit config files in ./config/"
echo "  2. Ensure ./config/*.yml are properly configured"
echo "  3. Run runtime container"
echo "  4. In runtime, execute:"
echo "     - rake db:initial_setup (first time)"
echo "     - rake canvas:compile_assets"
echo ""
echo "=========================================="
echo "Builder finished!"
